### ISSUE TITLE
Can't use or install plugin

### ISSUE THREAD

**Issue by bigtweekx** [txtsd/qB-IPT#1]
I was using this plugin fine for a few months and all of a sudden I can't see it anymore in the search plugin list. When I try installing it via the GUI i get an error message saying it can't be installed. If I manually copy it to %LOCALAPPDATA%/qbittorrent/nova/engines, the plugin does not show up in the list. However I do see a .pyc file created. Is this a personal issue or something wrong with the site/plugin? I have also tried fresh installs of qbittorrent and python with no luck.
I've also tried older versions with no luck. 

qBittorrent 4.1.7
Python version 3.7.4

I appreciate any help with this, thanks

**Comment by txtsd** [comment]
I'm not sure I can help with this unless there is some kind of debug log containing info about the plugin.

Could you try removing the file from the folder, downloading the latest version to your downloads folder, then installing as a local file from there?

**Comment by cheshmghermezi** [comment]
I got this on a fresh install: http://prntscr.com/q3wszd

**Comment by txtsd** [comment]
According to https://github.com/qbittorrent/search-plugins/issues/121, plugin support is going to be dropped in favor of better Jackett integration.

I've put in a fair bit of work in trying to get this plugin to work with qBt, but qBt refuses its own official plugins after a while. I will not be putting more time into it since the devs aren't leaning toward fixing plugin compatibility.
