### ISSUE TITLE
Plugin not supported

### ISSUE THREAD

**Issue by rehannali** [txtsd/qB-IPT#2]
I get an error while installing this plugin "This plugin isn't supported". This happened after the latest update.
I'm using Latest qBittorrent 4.1.9
Python= 3.7.5

**Comment by txtsd** [comment]
Happened to me too. I'm not sure what's going on with qbittorrent's recent updates. The installed file should still be available locally. Try installing that local file first. Then once it succeeds, try the link version.

**Comment by rehannali** [comment]
@txtsd I have one PC running Catalina and another one running Mojave. I'm facing a problem on Mojave. I tried with a local file and it is the latest one which I'm using on Catalina.

**Comment by txtsd** [comment]
Looks like it broke completely for me. I'm going to investigate further.

**Comment by rehannali** [comment]
@txtsd Hi, Any update related to this issue? This plugin now completely broken with qbittorrent 4.2.0.

**Comment by txtsd** [comment]
Sorry not yet. Might I recommend [Jackett](https://github.com/Jackett/Jackett) in the meantime?

**Comment by txtsd** [comment]
Update: According to https://github.com/qbittorrent/search-plugins/issues/121, plugin support is going to be dropped in favor of better Jackett integration.

I've put in a fair bit of work in trying to get this plugin to work with qBt, but qBt refuses its own official plugins after a while. I will not be putting more time into it since the devs aren't leaning toward fixing plugin compatibility.
